server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
  #配置访问controller的统一前缀
  servlet:
    context-path: /myfund

spring:
  primary-datasource:
      database: sql_server
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://10.20.34.122;DatabaseName=SecondaryData_New
      username: su
      password: ysmz,.123
      max-active: 10
      max-idle: 5
      min-idle: 5
  secondary-datasource:
      database: mysql
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/wxapplet?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: root
      max-active: 10
      max-idle: 5
      min-idle: 5
  thirdary-datasource:
    database: sql_server
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://10.20.34.122;DatabaseName=PrimaryData_New
    username: su
    password: ysmz,.123
    max-active: 10
    max-idle: 5
    min-idle: 5
  fourthary-datasource:
    database: sql_server
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://10.20.34.121;DatabaseName=CMS_NEW
    username: bd1
    password: bd1myfp
    max-active: 10
    max-idle: 5
    min-idle: 5

  #hibernate配置
  jpa:
#    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
    hibernate:
      primary-dialect: org.hibernate.dialect.SQLServer2008Dialect
      secondary-dialect: org.hibernate.dialect.MySQL5Dialect
      thirdary-dialect: org.hibernate.dialect.SQLServer2008Dialect
      fourthary-dialect: org.hibernate.dialect.SQLServer2008Dialect
      naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  #热部署
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启目录
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**

logging:
  config: classpath:log/logback-spring.xml
  #path: E:/wxapplet_log/
  #不显示大量自动配置的相关信息
  level:
    org.springframework.boot.autoconfigure: ERROR

debug: true


